// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQFiAzowfMbUqooGKCAKo_Vd76hSit1tg',
    appId: '1:177103983795:web:1713e4811a410200290cc6',
    messagingSenderId: '177103983795',
    projectId: 'flutter-demo-51336',
    authDomain: 'flutter-demo-51336.firebaseapp.com',
    storageBucket: 'flutter-demo-51336.firebasestorage.app',
    measurementId: 'G-PE40WKRG1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXTu4XTzDSIuoN8eYGuSRkGKUPS-S9-aQ',
    appId: '1:177103983795:android:cb73e57cec49094b290cc6',
    messagingSenderId: '177103983795',
    projectId: 'flutter-demo-51336',
    storageBucket: 'flutter-demo-51336.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDULM1aqJWyjUy6YV-ycoHSTuSWtva2GlU',
    appId: '1:177103983795:ios:40864cb243e9726e290cc6',
    messagingSenderId: '177103983795',
    projectId: 'flutter-demo-51336',
    storageBucket: 'flutter-demo-51336.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDULM1aqJWyjUy6YV-ycoHSTuSWtva2GlU',
    appId: '1:177103983795:ios:40864cb243e9726e290cc6',
    messagingSenderId: '177103983795',
    projectId: 'flutter-demo-51336',
    storageBucket: 'flutter-demo-51336.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQFiAzowfMbUqooGKCAKo_Vd76hSit1tg',
    appId: '1:177103983795:web:5eecab4f72523c2c290cc6',
    messagingSenderId: '177103983795',
    projectId: 'flutter-demo-51336',
    authDomain: 'flutter-demo-51336.firebaseapp.com',
    storageBucket: 'flutter-demo-51336.firebasestorage.app',
    measurementId: 'G-NQ9C17T91S',
  );
}
